### ISSUE TITLE
I am finding difficulty in reading codes in commit.

### ISSUE THREAD

**Issue by jack17529** [aredridel/how-to-read-code#4]
Can someone please tell how to read a diff code written here -
https://github.com/pyinstaller/pyinstaller/commit/b083d4db3b5f7394bae4f379fb336f15a3735830?diff=unified

**Comment by aredridel** [comment]
Hm. Perhaps! What's your goal in reading it? Solving a bug? Participating in the process?

**Comment by jack17529** [comment]
Just wanted to solve bug but don't know how many different repositories was this code taken.

I actually haven't read all the repositories of this project yet.

**Comment by aredridel** [comment]
Ah, tricky! I usually search for symbols in github, see if I can find the common elements. It's tricky though, to approach a large codebase. What's the bug you're looking for?

**Comment by jack17529** [comment]
Mam I am just a beginner so I have seen your profile , its very good  you contribute every day .How do you do so?

**Comment by aredridel** [comment]
I work a lot, and everything I touch I push upstream. I find bugs in things I use. If I find docs lacking, I write tweaks. There's no change too small for most projects. I've done a lot of side projects, too, solving little problems I have in work I do. I make contributing to projects a matter of habit. I do it a lot less when I'm working on a single closed source app.

I also write fiction and push that to private repos, so that shows too. If it comes out of my keyboard, there's a good chance it gets committed to git and pushed.

**Comment by jack17529** [comment]
Mam it's been 3 months I have been working on github , and I think you are the right person who can evaluate my github please see - https://github.com/jack17529

**Comment by aredridel** [comment]
What sort of evaluation? That's not really a service I provide though.
